#!/usr/bin/env bash
# Script displays 
# to infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invicible!!! when receiving a SIGTERM signal

trap 'echo "I am invicible!!!"' 15
while true; do
	echo "to infinity and beyond"
	sleep 2
done
