#!/usr/bin/env bash

# Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Modify user and port in nginx.conf
sed -i -E 's/#?user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i -E 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-available/default

# Change permissions on nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Restart nginx service
service nginx restart
